version: "3"
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  dynamodb-admin:
    image:
      aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb-local
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: sam
      AWS_SECRET_ACCESS_KEY: secret
    ports:
      - 8001:8001
